### ISSUE TITLE
Diff-hl foreground border issue

### ISSUE THREAD

**Issue by ianpan870102** [oneKelvinSmith/monokai-emacs#104]
The current face for diff-hl foreground and background result in a thin border being drawn around the git gutter. I have tried to **mimic the appearance of Sublime Text** and came up with the following tweak:

```emacs-lisp
  (diff-hl-insert      ((t (:background "#a6e22c" :foreground "#a6e22c"))))
  (diff-hl-delete      ((t (:background "#f83535" :foreground "#f83535"))))
  (diff-hl-change      ((t (:background "#e7db74" :foreground "#e7db74"))))
```

Which produces the **following result** (notice the git gutter style on the left fringe):

![image](https://user-images.githubusercontent.com/36686900/93287462-3292d100-f80c-11ea-9c4f-b50fbab2795e.png)

Let me know if a PR is welcome, and I can certainly make one!

**Comment by sdwolfz** [comment]
Could you please share an image of how this looks in Sublime?

**Comment by ianpan870102** [comment]
> Could you please share an image of how this looks in Sublime?

Sure, here you go:

![image](https://user-images.githubusercontent.com/36686900/93356478-c8ad1280-f871-11ea-8a53-18ea125aaac9.png)

**Comment by oneKelvinSmith** [comment]
This looks good to me. You're welcome to make a PR 👍🏽

**Comment by ianpan870102** [comment]
PR created, ready for review!

**Comment by sdwolfz** [comment]
Since the PR was merged, issue can be closed, right?

**Comment by ianpan870102** [comment]
Yup, closing issue.
