### ISSUE TITLE
Monokai always deletes face customizations when entering git-commi-mode

### ISSUE THREAD

**Issue by tuhdo** [oneKelvinSmith/monokai-emacs#18]
To reproduce:

- Start with bare Emacs (move you ~/.emacs.d elsewhere).
- Install `monokai-theme`
- Install `magit`.
- Load monokai: 
```lisp
(load-theme 'monokai t)
```
- `M-x customize-theme` and untick monokai. Emacs returns to its original theme.
- Commit something. A buffer with `git-commit-mode` pops up, and instead of keeping the current theme, Emacs returns to `monokai` theme.

`monokai-theme` is just an example. It happens with other face customizations as well. I also checked that no code is added to `git-commit-mode-hook`. Other themes do not have this problem. I had a few customizations related for monokai theme, but got reset to the default when activating `git-commit-mode` for committing.

**Comment by oneKelvinSmith** [comment]
Closing...
