### ISSUE TITLE
eval: Invalid function: "#FD5FF0"

### ISSUE THREAD

**Issue by romanjoe** [oneKelvinSmith/monokai-emacs#31]
Hello, thank you for your work, Kelvin! I really appreciate your approach to provide monokai for emacs, as this is my favorite color theme by now.

My problem is described in the title. I have this error, any time i start emacs. I can't even understand, why a hex color is interpreted as function. 
Nevertheless theme is working - colors are displaying, despite this error. 

Could please suggest, what it may be? I run 
GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.3) under Manjaro linux.

Thank you!

**Comment by rfinz** [comment]
I can confirm this issue. I'm on 24.4 on Mac OSX Yosemite 10.10.1. 

Did some preliminary looking at the code and was similarly unable to determine why that particular hex value is the one causing the error.

**Comment by legends2k** [comment]
I too ran into this issue, but only when I try to call the function `highlight-changes-mode`, the minibuffer barks back `Invalid function: "#FD5FF0"`.

**Comment by arun-s** [comment]
Here is the fix, a ' is missing infront of (,magenta,violet) so it's not being presented as a list

```
diff --git a/themes/monokai-theme.el b/themes/monokai-theme.el
index 5414e57..4db679c 100644
--- a/themes/monokai-theme.el
+++ b/themes/monokai-theme.el
@@ -5334,7 +5334,7 @@ Also affects 'linum-mode' background."
    `(magit-diff-use-overlays nil)
 
    ;; highlight-changes
-   `(highlight-changes-colors (,magenta ,violet))
+   `(highlight-changes-colors '(,magenta ,violet))
 
    ;; highlight-tail
    `(highlight-tail-colors
```

**Comment by oneKelvinSmith** [comment]
Nice 😃

Do you mind making a pull request? 

Also, can you direct me to a good resource that explains the ' syntax? I get very confused between it and the back-tick (and when to use it).

p.s. This has made my day.

**Comment by arun-s** [comment]
Sorry, I just saw your reply. Looks like you have already checked in the fix.

As for your question, I didn't know either but was able to locate a good explanation in the emacs manual :)
http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html#Backquote

Backquote(`) is the same as ('), except that it allows selective expansion inside the list by way of the ',' marker. Hope this helps.

p.s. I am using your monokai port as my default theme and totally love it. Thanks for the hard work!
