### ISSUE TITLE
Red background in org-mode-line-clock-overrun makes it impossible to read the clock

### ISSUE THREAD

**Issue by aagaard** [oneKelvinSmith/monokai-emacs#32]
This is favorite theme for emacs and I really think it presents emacs well.

But it is very hard to read the clock in org-mode, when the clock is overran. The red background and the grey text makes it almost impossible to read for me. 

![selection_190](https://cloud.githubusercontent.com/assets/540810/5797211/362b48f6-9fb6-11e4-99e3-7e92004a8ec6.png)

**Comment by oneKelvinSmith** [comment]
@aagard Agreed. I'm sorry it took so long. Next time, please open a pull request with the change. 

Thank you for the feedback though.
