### ISSUE TITLE
Hard to differentiate `monokai-hl` from `monokai-hl-line`

### ISSUE THREAD

**Issue by zane** [oneKelvinSmith/monokai-emacs#35]
The background colors for `monokai-hl` and  `monokai-hl-line` are very close, making it hard to see selections on the current line if you use `transient-mark-mode`.

**Comment by sunesimonsen** [comment]
It is a very beautiful theme, but I agree with this problem. I think it would be better with a darker background maybe even black and tone down the hl-line color to be just a little visible and make the hl color just a bit darker. 

This works better for me, but can of cause be refined:

       (monokai-bg               "#000000")
       (monokai-hl-line          "#141410")
       (monokai-hl               "#39382E")

**Comment by oneKelvinSmith** [comment]
@zane, @sunesimonsen, I tried to maintain the highlights as I found them, but I agree that this is a problem. I'll give it more contrast.

**Comment by sunesimonsen** [comment]
That is awesome news. I'm extremely happy with the theme, this is the only
thing that is annoying. Thanks for the great work.

Kind regards
Sune
