### ISSUE TITLE
splash when I press C-l on long file with 4 panels 

### ISSUE THREAD

**Issue by xuxiangyang** [oneKelvinSmith/monokai-emacs#37]
*.rb or *.el files in 4 panels, like this 
![image](https://cloud.githubusercontent.com/assets/4926529/7957376/7bfd5bda-0a19-11e5-9aa6-2e347141f95d.png)

when I press C-L quickly，the screen splashes. what can I do to solve this problem? zenburn has this problem, too.

thanks for your help

**Comment by xuxiangyang** [comment]
here is my emacs [config](https://github.com/xuxiangyang/myconf/blob/master/emacs)

**Comment by oneKelvinSmith** [comment]
Can you give me more context on how you are running emacs? Like which operating system you're using and if you are running emacs as a gui or in the terminal.

I'm not really sure where to start with this issue. My immediate advice is: Don't press C-L quickly...

**Comment by oneKelvinSmith** [comment]
Ok, I'm still not sure how to recreate/address this. I'm closing the issue for now. @xuxiangyang please reopen if you are still experiencing issues.
