### ISSUE TITLE
"Error face-attribute: Invalid face: t" when using org-html-export

### ISSUE THREAD

**Issue by mikedmcfarland** [oneKelvinSmith/monokai-emacs#38]
I'm encoutering the error: `Error face-attribute: Invalid face: t`

When trying to export html in org-mode using: `org-html-export-to-html`.
When I load other themes (at startup) I have no problems.

If I load any theme *after* loading monokai, Same error occurs. The act of loading the theme at any point causes the problem.

I just pulled and used the code from this repo and confirmed the same behavior.

if it helps my emacs version is: 24.5.1, and I'm up to date on maint for org-mode (2dec59b4051589c7033901ed0c92625f1beecb46).

I'm no emacs expect, and so I'm not sure how to debug the problem. Any thoughts?

**Comment by bkoropoff** [comment]
Looks like monokai sets some broken inherit attributes.  The following snippet will clear them out.

```elisp
;; Fix broken face inheritance
(let ((faces (face-list)))
  (dolist (face faces)
    (let ((inh (face-attribute face :inherit)))
      (when (not (memq inh faces))
        (set-face-attribute face nil :inherit nil)))))
```

**Comment by oneKelvinSmith** [comment]
@bkoropoff, thanks for the heads up. I've removed `:inherit t` wherever it appeared in the theme.
@mikedmcfarland, I'm no expert either. Can you try again?

**Comment by mikedmcfarland** [comment]
I'll check it out this weekend and let you know.
