### ISSUE TITLE
No colors in ERC buffers

### ISSUE THREAD

**Issue by nloyola** [oneKelvinSmith/monokai-emacs#39]
I'm using Emacs 24.5.1 on Ubuntu 15.04 and the latest version of this theme. When I start ERC none of the buffers that get created have any colors. I've attached a screen shot.

Is there a way to fix this?

Thanks

![emacs_monokai_erc_no_colors](https://cloud.githubusercontent.com/assets/334607/10398380/f44c8016-6e69-11e5-913c-70cf29666b25.png)

**Comment by nloyola** [comment]
I just tried loading up ERC with the monokai theme disabled and I get the same results. I'm closing this issue.

**Comment by oneKelvinSmith** [comment]
Ah thank you.
