### ISSUE TITLE
Color approximation in terminal

### ISSUE THREAD

**Issue by Evidlo** [oneKelvinSmith/monokai-emacs#42]
I don't know if this can be fixed in the theme, but the terminal color approximation is way off for diff highlighting.

* X11 emacs
![orig](http://i.imgur.com/eJsSTAb.png)
* rxvt-256color
![magentaviolet](http://i.imgur.com/moAGgGF.png)

**Comment by oneKelvinSmith** [comment]
Issue #42! 

I think this should be fixable. I'll have a look tonight.
