### ISSUE TITLE
Use same height for all headings in org-mode

### ISSUE THREAD

**Issue by kshenoy** [oneKelvinSmith/monokai-emacs#45]
I tried setting `monokai-use-variable-pitch` to `nil` but the headings in org-mode still have different heights. I use [use-package](https://github.com/jwiegley/use-package) and set the variable like so:

    (use-package monokai-theme
      :config
        (setq monokai-use-variable-pitch nil))

I verified with `describe-variable` that `monokai-use-variable-pitch` was indeed set to `nil` 

What am I missing over here?

**EDIT**: Changing `:config` to `:init` doesn't seem to help either

    (use-package monokai-theme
      :init
        (setq monokai-use-variable-pitch nil))

**Comment by mineo** [comment]
You need to set `monokai-height-plus-{1,2,3,4}` like so:

```elisp
  (setq monokai-height-plus-1 1.0
        monokai-height-plus-2 1.0
        monokai-height-plus-3 1.0
        monokai-height-plus-4 1.0
        monokai-height-minus-1 1.0)
```

before loading the theme (there's also a [question](https://stackoverflow.com/questions/24992300/how-to-customize-emacs-themes-without-editing-the-theme) on emacs.sx about that, but it doesn't use `use-package`).

**Comment by oneKelvinSmith** [comment]
Thanks @mineo!

@kshenoy does this help?

**Comment by oneKelvinSmith** [comment]
Going to close this. Please let me know if it's still a problem.

**Comment by kshenoy** [comment]
Hi, sorry for the late response. This does exactly what I asked for. Thanks :+1:

**Comment by s-surineni** [comment]
Awesome. It would have been better if there was a switch to turn this on and off
