### ISSUE TITLE
How to add background color with mmm mode?

### ISSUE THREAD

**Issue by pengzhendong** [oneKelvinSmith/monokai-emacs#46]
In mmm mode, it will use the default background color.

**Comment by oneKelvinSmith** [comment]
Hi @pengzhendong,

I'm sorry that it took me so long to reply. 

Can you give me a screenshot / example. I'm looking into it now.

**Comment by oneKelvinSmith** [comment]
Ok, looks like I/we need to add support for the mmm faces defined here: [mmm-vars.el](https://github.com/purcell/mmm-mode/blob/master/mmm-vars.el)

**Comment by pengzhendong** [comment]
OK, thanks for your reply.
