### ISSUE TITLE
the default foreground color is too bright

### ISSUE THREAD

**Issue by futurist** [oneKelvinSmith/monokai-emacs#48]
How to change default foreground color? if it's too bright

Thanks!

**Comment by oneKelvinSmith** [comment]
Hey @futurist, sorry about the delay.

You can try this in you init file:

```lisp
 (set-face-attribute 'default t :foreground "#DDDDDD") ;; use the hex value for the colour you would like.
```

Alternatively, you could customize the face (the styling applied to a part of the text) from within emacs with:
```lisp
M-x customize-face RET face RET ;; in your case 'face' would be 'default'
```

If you'd like more detail please check out:
[Specific Customization on gnu.org](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specific-Customization.html)
[Set Fonts on Emacs Wiki](https://www.emacswiki.org/emacs/SetFonts)
