### ISSUE TITLE
[request] Make code-blocks in org-mode stand out more

### ISSUE THREAD

**Issue by moesasji** [oneKelvinSmith/monokai-emacs#50]
Currently the org code-blocks in monokai by default get displayed as comments, making them hard to see. Even when setting 'org-src-fontify-natively' to true it remains hard to see where the code-blocks are as then they look very similar to the rest of the text. Would it be possible to change the default face used for org-block-* to something that makes them stand out better?

Although it is a light theme, the Leuven theme has this implemented and illustrates it best. See http://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html for the screenshot. In that theme it is immediately clear what code-blocks, which is very helpful.

**Comment by oneKelvinSmith** [comment]
I'll have a look tonight or tomorrow. If leuven does it, we can too :)

**Comment by oneKelvinSmith** [comment]
@moesasji let me know if this works for you.

**Comment by moesasji** [comment]
Thanks for the quick response. This almost works, but not completely:

1) If I don't use syntax highlighting in the code-blocks the face is indeed org-block and it works as expected.

2) If I set org-src-fontify-natively to true the face becomes org-block-background, so it doesn't work as expected. 

The fix that works for me is adding the following code to set the correct face only for the background for this face:

`(org-block-background`
     `((,class (:background ,monokai-gray))`
      `(,terminal-class (:background ,terminal-monokai-gray))))`

With this added the block stands out correctly both with and without the syntax highlighting.

**Comment by oneKelvinSmith** [comment]
Ok, I'll put that in today. 

Unless you want to make a pull request?

**Comment by moesasji** [comment]
Please go ahead as the change is pretty obvious.
