### ISSUE TITLE
monokai theme conflicts with ivy package

### ISSUE THREAD

**Issue by zilongshanren** [oneKelvinSmith/monokai-emacs#52]
For more details, please refer to 
https://github.com/abo-abo/swiper/issues/506#issuecomment-217713073

**Comment by moesasji** [comment]
This to me looks like a typo as ivy-current-match currently has `:background highlight`. This probably should be something like `:background ,monokai-highlight`

btw) the above change gets rid of the error-message when using ivy/swiper, but it looks way too bright to me.

**Comment by zilongshanren** [comment]
@abo-abo  Thoughts?

**Comment by oneKelvinSmith** [comment]
Yeah, this was an error I introduced. Oops.

https://github.com/oneKelvinSmith/monokai-emacs/pull/54 this should have resolved it. Thanks to @abo-abo again.
