### ISSUE TITLE
the error: Invalid face box: :color, "#3D3D3D", :style, unspecified, :line-width, 1

### ISSUE THREAD

**Issue by xux1217** [oneKelvinSmith/monokai-emacs#53]
I like this theme, but when I use the melpa to update the theme to 2.0.0, it reports the error: "set-face-attribute: Invalid face box: :color, "#3D3D3D", :style, unspecified, :line-width, 1".

When I use the git to clone the project, and checkout the 0.2.7 version, it is perfect.

I don't know why, please tell me how to fix it, thanks~

**Comment by oneKelvinSmith** [comment]
I'll look into it tonight.

**Comment by oneKelvinSmith** [comment]
@xux1217 thank you for raising this, I didn't test properly in the terminal and missed the bug :(

Please try the latest version in Melpa, hopefully you have a more pleasant experience.
