### ISSUE TITLE
Byte compilation

### ISSUE THREAD

**Issue by joshdekock** [oneKelvinSmith/monokai-emacs#57]
I see you have disabled byte compilation with `;; no-byte-compile: t`
 Is there a particular reason for this? It seems to work fine when compiled.

**Comment by joshdekock** [comment]
It's on all themes apparently, so I'm guessing it's just convention.

**Comment by oneKelvinSmith** [comment]
Yeah, a lot of the stuff is (kind of) cargo-culted in. I'd be keen to know why it's included in all themes or why you felt that it might not have been necessary.

Cheers 👍

**Comment by joshdekock** [comment]
I'm a new emacs user, and coming from other editors even a 1 seconds startup time is quite large (yes, I know about daemon mode, I'm using that until I can find a way to properly speed everything up).

The reason I didn't think it was necessary is because a theme is mostly just setting values (or as far as I can tell by skimming through it), and I didn't think there would be any side effects of byte-compiling something which only set some values. This is probably very naive, but as I said, I'm a new emacs user.

I'm going to do some more investigation into it, I'll post back here if I find anything interesting.
