### ISSUE TITLE
How to overwrite a specific variable used inside the theme

### ISSUE THREAD

**Issue by diego-alvarez-hs** [oneKelvinSmith/monokai-emacs#59]
Sorry, this is more a question I couldn't find an answer on internet :(

Is there any way to overwrite in my config a defined variable in the theme? i.e.:
https://github.com/oneKelvinSmith/monokai-emacs/blob/02c5f5d5a5d3ee93a1daa16117471197817f3bc8/monokai-theme.el#L104

So, when I redefined `(monokai-yellow "red")` all the faces that are using that color are now going to show a "red" color.

would we need to expose, let's say the primary colors, as `(defcustom monokai-yellow..` ?

Hope this make sense!

And thanks for this beautiful theme, I just want to tweak a few colors :)

**Comment by oneKelvinSmith** [comment]
Hi @diego-alvarez-hs, 

Sorry about taking so long to reply. I was away on holiday. 

I think you are correct in that we would need to expose the variables via `defcustom` constructs.

Alternatively you can customize a globally defined face:

```lisp
(custom-set-faces
  '(font-lock-keyword-face ((t (:foreground "red" :weight normal)))))
```

**Comment by diego-alvarez-hs** [comment]
@oneKelvinSmith before starting working with a possible PR are you OK exposing those variables?

I don't want to change specific faces as I'm interested on changing just the primary colors on monokai, as this theme it's doing an excellent job and has a lot of faces customized.

So, with changing just 4 primary colors, this is the result:

![image](https://cloud.githubusercontent.com/assets/12563308/17238161/3a4eecc6-550e-11e6-9860-6f5fe327c5f1.png)

And this is the original:
![image](https://cloud.githubusercontent.com/assets/12563308/17238169/43579ba6-550e-11e6-80df-6c2fb6fdb517.png)

Please let me know if you're Ok with this and I'll send the PR.

**Comment by oneKelvinSmith** [comment]
I'm definitely open to exposing the variables. I'd like to see the PR. 

My intuition is that I would (then) want to customize any of the primary or adaptive colours, but I think that starting with the 4 you'd like to change will be great.
