### ISSUE TITLE
Is it possible to set monokai-highlight similar to monokai-highlight-line?

### ISSUE THREAD

**Issue by lbsx** [oneKelvinSmith/monokai-emacs#61]
Code in emacs without selection:
![monokai_without_selection](https://cloud.githubusercontent.com/assets/441707/17646898/42751330-6210-11e6-8762-c31461268121.png)

Selection in emacs:
![selection_monokai_emacs](https://cloud.githubusercontent.com/assets/441707/17646899/430dda70-6210-11e6-9075-962ba32bee9a.png)

Selection in Sublime:
![selection_sublime](https://cloud.githubusercontent.com/assets/441707/17646971/eb525620-6210-11e6-9fd0-c2a2f98e51b9.png)

**Comment by oneKelvinSmith** [comment]
@lbsx try the latest version of the theme please. I've updated the colours and extended the number of custom face functions. So people can override the highlight colours if they prefer another:

```lisp
(setq monokai-highlight      "#FFB269"
      monokai-highlight-alt  "#66D9EF")
```

This is what I was able to get to:


<img width="278" alt="highlight_emacs" src="https://cloud.githubusercontent.com/assets/1781199/17649597/52340076-6231-11e6-8ace-605e6c510a11.png">

**Comment by lbsx** [comment]
Thank you. I've tried the latest version and it works fine. But I found that there seems to be a conflict between highlight-symbol and global-hl-line-mode.

I have (global-hl-line-mode t) in my dot emacs and executed highlight-symbol-at-point on monokai-highlight-line.

Cursor not on the same line:
![a](https://cloud.githubusercontent.com/assets/441707/17649900/3a8aa380-6272-11e6-960c-e05bb08fad72.png)

Cursor on the same line:
![b](https://cloud.githubusercontent.com/assets/441707/17649902/41246514-6272-11e6-85f0-b2818edf94be.png)

Could this be fixed?

BTW, are you using rainbow-delimiters mode?

**Comment by oneKelvinSmith** [comment]
So it looks like `hl-line-mode` uses [overlay properties](https://www.gnu.org/software/emacs/manual/html_node/elisp/Overlay-Properties.html) to apply the line highlight. This will always take precedence over [text properties](https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Properties.html#Text-Properties) when applying colours.

The faces applied when evaluating `highlight-symbol-at-point` are defined en `hi-lock.el`. These faces seem to be applied using font lock by default which change the _text properties_ and do not use _overlays_. See this screenshot (I found the documentation by using `find-library`): 

<img width="466" alt="hl-lock-uses-font-lock" src="https://cloud.githubusercontent.com/assets/1781199/17651663/aaa21e50-6263-11e6-850c-467e6a4111a9.png">

A similar issue [here](https://stackoverflow.com/questions/6562424/emacs-hl-line-mode-conflicts-with-highlight-phrase) suggests using a brighter foreground colour for the hi-lock faces. But it looks like the foreground face isn't coming through on your system. 

Which is weird.

 Here is what it looks like when I try it:

<img width="518" alt="foregrounds-apply" src="https://cloud.githubusercontent.com/assets/1781199/17651684/1ebb2aac-6264-11e6-95b6-a981376cba68.png">

I'm not sure where to go next with this, the highlight precedence breaks my brain...


p.s. Yes, I am using rainbow delimiters. I'm actually using [Spacemacs](http://spacemacs.org/), which is usually a pleasant experience.

**Comment by lbsx** [comment]
I've tried to customize highlight-symbol-foreground-color to a brighter color, but it's not a perfect solution.

And I found [hl-anything-emacs](https://github.com/hl-anything/hl-anything-emacs) works with highlight-symbol. I'll try it.

**Comment by oneKelvinSmith** [comment]
Ok, that looks cool.

It seems like they specify colours like using these functions: 
```lisp
(defcustom hl-highlight-foreground-colors '("snow"
                                            "snow"
                                            "black"
                                            "black"
                                            "snow"
                                            "snow"
                                            "snow"
                                            "black"
                                            "snow"
                                            "snow")
  "The foreground colors for `hl-highlight-thingatpt-global' and
`hl-highlight-thingatpt-local'."
  :type '(repeat color)
  :group 'hl-anything)

(defcustom hl-highlight-background-colors '("firebrick"
                                            "Orange"
                                            "gold"
                                            "green1"
                                            "DeepSkyBlue1"
                                            "dark blue"
                                            "blue violet"
                                            "gray90"
                                            "gray60"
                                            "gray30")
  "The background colors for `hl-highlight-thingatpt-global' and
`hl-highlight-thingatpt-local'."
  :type '(repeat color)
  :group 'hl-anything)
```

I'm not sure if that's something this theme should be responsible for.

**Comment by lbsx** [comment]
I don't think it's relevant to the theme. I will close the issue.
