### ISSUE TITLE
background color displays differently in terminal

### ISSUE THREAD

**Issue by jjackaman** [oneKelvinSmith/monokai-emacs#64]
Can the background color (monokai-bg "#272822") be made to work in the terminal too?

In iterm2 emacs displays the background color as #1c1c1c.

**Comment by oneKelvinSmith** [comment]
Hey @jjackaman. I'm not sure if things have changed since [this issue](https://github.com/oneKelvinSmith/monokai-emacs/issues/2) but when I tried using true colours for the terminal client, the background came out green.

**Comment by oneKelvinSmith** [comment]
Closing until it resurfaces.
