### ISSUE TITLE
highlight-update branch (evil-search-highlight-persist)?

### ISSUE THREAD

**Issue by braham-snyder** [oneKelvinSmith/monokai-emacs#66]
I'm just wondering why you're holding off on merging the highlight-update branch into master--so far, the only trouble I've encountered is that `evil-search-highlight-persist-highlight-face` is the same color as `hl-line`. While not perfect, is that not preferable to master (where `evil-search-highlight-persist-highlight-face`--the same color as comments--obscures matched comment text)?

Or is it something else? The `linum-mode` background? Region vs. match? `holy-mode`? For reference, here's a picture of what I'm seeing with highlight-update merged into master (after an `evil-ex-search` for "fill"):

![screen shot 2016-12-03 at 6 43 16 pm](https://cloud.githubusercontent.com/assets/7269114/20863222/617453e2-b989-11e6-90ba-c58594ddc8aa.png)

Thanks for the primo theme!

**Comment by oneKelvinSmith** [comment]
I've just been distracted by my day job :) 

The lastest release should sort these issues out. Thanks for the reminder.

**Comment by braham-snyder** [comment]
Awesome--thanks!
