### ISSUE TITLE
Org code blocks

### ISSUE THREAD

**Issue by agroschim** [oneKelvinSmith/monokai-emacs#67]
Since you changed the value of `monokai-gray` to a much lighter color in commit 65970ea4a15891962784701c75c391c19023a559 org code blocks especially with enabled syntax highlighting became unreadable, might I suggest changing the value of `org-block-background` from `monokai-gray` to `monokai-highlight-alt`?

**Comment by oneKelvinSmith** [comment]
Hi @agroschim Please have a look at the latest version and let me know if this works for you. I found it difficult to notice the  difference, but I was working in a dark room.

**Comment by agroschim** [comment]
Works fine for me now. Thank you.

I should have added that I am using native syntax highlighting in code blocks.

**Comment by oneKelvinSmith** [comment]
Cool 👍
