### ISSUE TITLE
Current 'Search' highlight is lighter over a light background.

### ISSUE THREAD

**Issue by codesoverhill** [oneKelvinSmith/monokai-emacs#72]
Thanks for the wonderful colorscheme.

![screenshot_2017-05-07_00-34-13](https://cloud.githubusercontent.com/assets/28491132/25775215/0d51cc28-32be-11e7-9db6-b4b407e092af.png)

Am not sure if this is an issue with the theme but search string foreground is mostly light colour over light background. Is this theme configuration? And can I modify it in my init.el?

Am new to emacs and my init.el is minimal and being built. Am running emacs 25.2.1 on Linux Mint. Looking at closed issue, I don't see anyone else have it.
```
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (monokai)))
 '(custom-safe-themes
   (quote
    ("f78de13274781fbb6b01afd43327a4535438ebaeec91d93ebdbba1e3fba34d3c" default)))
 '(package-selected-packages (quote (monokai-theme))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by oneKelvinSmith** [comment]
Heya @codesoverhill , thanks for the question :)

the isearch face inherits the foreground colours because it inherits from region. Region inherits the syntax highlighting when selecting text because I prefer to maintain it. I'll try out disabling that just for isearch matches (I think it might make sense with the brighter colours).

In the mean time you could try add something like this to your config:

```lisp
(set-face-attribute 'isearch nil
                    :foreground monokai-background ;; replace with your colours
                    :background monokai-violet)    ;; of choice e.g. "#A6E22E"
```

Let me know if that helps.

**Comment by codesoverhill** [comment]
@oneKelvinSmith, thank you. The suggestion worked fine.
