### ISSUE TITLE
Optimize linum/nlinum faces in monokai-theme 

### ISSUE THREAD

**Issue by seagle0128** [oneKelvinSmith/monokai-emacs#74]
Hi, I found this solution to optimize linum/nlinum faces in monokai-theme, but I have no idea how to create a PR for the theme. Please refer to the snippet and let me know your opinion. Thanks!

```elisp
  ;; FIX: show-paren-mode erroneously highlights the left margin
  ;; https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-10/msg01050.html
  (custom-set-faces '(linum ((t (:inherit default)))))
```

**Comment by oneKelvinSmith** [comment]
I'll have a look. Thank you.

**Comment by seagle0128** [comment]
After some research, I think it may need to handle this issue in Emacs.

**Comment by oneKelvinSmith** [comment]
This fell off my plate. Is there something I need to look into?
