### ISSUE TITLE
Spacemacs. Recent update broke monokai-emacs

### ISSUE THREAD

**Issue by voger** [oneKelvinSmith/monokai-emacs#77]
I did a packages update today in my spacemacs installation and now I get this error message in my \*Messages\* buffer

`(Spacemacs) Warning: An error occurred while applying the theme "monokai", fallback on theme "spacemacs-dark". 
Error was: (invalid-function ((, monokai-256-class) (:foreground (, monokai-256-yellow) :weight bold)))`

I don't know if this is monokai-emacs issue or a Spacemacs issue but I thought of asking here first.

**Comment by oneKelvinSmith** [comment]
Oh dear.
