### ISSUE TITLE
Tooltip colors

### ISSUE THREAD

**Issue by seagle0128** [oneKelvinSmith/monokai-emacs#78]
I suggest to change tooltip background from green to yellow. Green is ugly for the tooltip especially using company-quickhelp to show help.

```elisp
   `(tooltip
     ((,monokai-class (:background ,monokai-yellow-hc
                                   :foreground ,monokai-background
                                   :inherit ,monokai-pitch))))
```
I can make a PR if you are fine.

**Comment by oneKelvinSmith** [comment]
I'm happy for you to make a PR 👍

**Comment by seagle0128** [comment]
@oneKelvinSmith  Please merge PR #80 as well. I forgot to change pos-tip colors. it should be same as tooltip colors. Thanks!
