### ISSUE TITLE
Differentiate color for font-lock-doc-face and font-lock-comment-face

### ISSUE THREAD

**Issue by avigan** [oneKelvinSmith/monokai-emacs#88]
Could you please create a different color name for `font-lock-doc-face` and `font-lock-comment-face`? This would be very useful when for editing languages like python.

**Comment by oneKelvinSmith** [comment]
Ok, I've changed it to yellow (the same colour as strings). This seems the most reasonable change to me.

![comment_vs_doc](https://user-images.githubusercontent.com/1781199/34530241-6c255502-f0a6-11e7-97d9-e347c6debe97.png)

**Comment by avigan** [comment]
Thanks a lot!
