### ISSUE TITLE
Please add a licence.

### ISSUE THREAD

**Issue by demonchild2112** [oneKelvinSmith/monokai-emacs#92]

**Comment by sdwolfz** [comment]
The license is present inside the main file:

https://github.com/oneKelvinSmith/monokai-emacs/blob/5a3fa999f4f1ab2eeabf13a78d26eba7c1716051/monokai-theme.el#L3-L20

**Comment by oneKelvinSmith** [comment]
Ok, I've added a `LICENSE.md` file because it's cool and you can search for it with github: https://help.github.com/articles/licensing-a-repository/#searching-github-by-license-type.
