### ISSUE TITLE
Minibuffer / Echo area background color

### ISSUE THREAD

**Issue by jlagneau** [oneKelvinSmith/monokai-emacs#93]
Is it possible to edit the background color of the area below the mode-line? I'm looking at the source code but I can't see anything relevant. My aim is to make it the same color of my mode-line (on which I removed the borders). Any pointer would be greatly appreciated.

**Comment by oneKelvinSmith** [comment]
Can you provide an annotated picture of what you mean? It might make it easier for me.

**Comment by oneKelvinSmith** [comment]
I think you might be referring to the [echo area](https://www.emacswiki.org/emacs/EchoArea). Looks like you can change the face (color and text) with: 
```lisp
 (with-current-buffer (get-buffer " *Echo Area 0*")
    (setq-local face-remapping-alist '((default (:backgroud ,monokai-highlight)))))
```

Or
```lisp
(with-current-buffer " *Echo Area 0*" 
  (face-remap-add-relative 'default '(:inherit mode-line)))
```

Or some variation of the above. I haven't tested this though.

**Comment by jlagneau** [comment]
Hello and thanks a lot for your quick reply.

I'm talking about the mini-buffer & the echo area, both of them overlap in the same area depending on the situation (in red on the screenshot).

![minibuffer](https://user-images.githubusercontent.com/7811277/37779200-223ba12a-2dec-11e8-8360-27b0e984c4b4.png)
I have attempted several things in my scratch buffer to try things out but I couldn't find anything that suit my needs. Something like this was the closest to what I want to achieve:

```elisp
(dolist (buf (list " *Minibuf-0*" " *Minibuf-1*" " *Echo Area 0*" " *Echo Area 1*"))
    (when (get-buffer buf)
      (with-current-buffer buf
        (setq-local face-remapping-alist '((default (:background "green")))))))
```

But it doesn't work in every situation. When the echo area is inactive/empty it doesn't apply in some cases, or when I start a command with a prompt like `M-x`, only that portion of the mini-buffer is colored.

I know it's possible to style that portion of emacs to a different color than the default background since [I've seen it on the "doom" configuration of emacs](https://github.com/hlissner/emacs-doom-themes/tree/screenshots) (I even installed it to check if it was indeed possible, but I'm not a huge fan of using a distro for something as trivial as this) and I was wondering if you maybe had a variable definition of some sort to modify it directly in this theme. I've since then browsed the code a bit on the default doom repository and the themes repository but I couldn't figure it out (my Elisp understanding is lower than what I would like). It might be a better place to ask on these repositories directly though.

Feel free to close the issue (it was more a question to begin with).

**Comment by oneKelvinSmith** [comment]
Ooh Doom looks like a cool collection. I'll have a look later and see if I can get this figured out.

**Comment by jlagneau** [comment]
Just to let you know @oneKelvinSmith (and if some other people search for it), I finally found out how this was done in doom emacs: [solaire-mode](https://github.com/hlissner/emacs-solaire-mode) (from the same author as doom and doom themes. After a few tests, I customized the solaire's face and a couple of other things and I got what I wanted:

![screenshot_20180330_211010](https://user-images.githubusercontent.com/7811277/38150413-01b5bc5a-345f-11e8-8149-f5f801006b4d.png)

(It's actually not too hard to implement if you ever feel like supporting this package)
