### ISSUE TITLE
emacsclient with monokai theme is just ugly (green background)

### ISSUE THREAD

**Issue by hjpotter92** [oneKelvinSmith/monokai-emacs#97]
Quite similar to #2 and #64. I've tried several different terminals and modes (inside/outside of multiplexer like `tmux`/`screen`). If I create a new `-nw` (no-window) emacs inside shell, sometimes the older one gets bluish background, and sometimes it goes black.

See the screenshots below:

All 3 of them are green (top-left to right):
 * tmux inside Terminator
 * urxvt
 * uxterm

![2018-08-17_02_03_41](https://user-images.githubusercontent.com/3393533/44233837-94625600-a1c2-11e8-8fcb-84cc93273374.png)

and now, if I open `gnome-terminal`:
 * see that urxvt changes to blue background, and
 * uxterm changed to black background colour.

![2018-08-17_02_07_56](https://user-images.githubusercontent.com/3393533/44233918-ce335c80-a1c2-11e8-9088-fe47de5641be.png)

**Comment by lemon0910** [comment]
terminal emacs is not beautiful like gui emacs too

**Comment by hjpotter92** [comment]
> terminal emacs is not beautiful like gui emacs too

but that's not the case when I disable monokai theme, and use the default one.

**Comment by sdwolfz** [comment]
@hjpotter92 maybe this guide will help you set up your terminal colors: https://github.com/syl20bnr/spacemacs/wiki/Terminal

**Comment by hjpotter92** [comment]
@sdwolfz yup, been working with it for a week now. That does indeed work.

Closing this issue.
